default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: dbt_rw
      password: compost
      dbname: postgres
      schema: reporting
      threads: 4