spring:
  application:
    name: scanner
  scan-pool-size: 1
  scan-count: 3
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: scanner_rw
    password: brownies
  jpa:
    properties:
      hibernate:
        default_schema: raw_measurements
        jdbc:
          batch_size: 1
    hibernate:
      ddl-auto: update