services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    volumes:
      - ./docker-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: gradient
