spring:
  application:
    name: scanner
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: scanner_rw
    password: brownies
  jpa:
    properties:
      hibernate:
        default_schema: raw
        jdbc:
          batch_size: 1
    hibernate:
      ddl-auto: update

scanner:
  pool-size: 3
  count: 10
  write-delay-ms-min: 1
  write-delay-ms-max: 10
