create table measurement
(
    measurement_id    bigint generated by default as identity
        primary key,
    measurement_value double precision not null,
    scan_id           bigint,
    x                 integer,
    y                 integer,
    -- spring boot will not automatically create the modified_at column, so we need to do it manually
    modified_at       timestamp default CURRENT_TIMESTAMP
);

alter table measurement
    owner to scanner_rw;

