create schema raw;
create schema config;
create sequence raw.scan_id_sequence start with 1 increment by 1;

create table raw.measurement
(
    measurement_id    bigint generated by default as identity primary key,
    measurement_value double precision not null,
    scan_id           bigint,
    x                 integer,
    y                 integer,
    modified_at       timestamp default current_timestamp
);

create table config.grid
(
    id          integer primary key,
    template_id integer,
    x           integer,
    y           integer
);

-- seed a tiny multi-template grid: template 3 has 4 points, template 5 has 9 points
-- templates with intentionally different sizes so the "varying counts" assertion has signal to detect
insert into config.grid (id, template_id, x, y)
values (1, 3, 0, 0),
       (2, 3, 1, 0),
       (3, 3, 0, 1),
       (4, 3, -1, 0),
       (5, 5, 0, 0),
       (6, 5, 1, 0),
       (7, 5, -1, 0),
       (8, 5, 0, 1),
       (9, 5, 0, -1),
       (10, 5, 1, 1),
       (11, 5, -1, -1),
       (12, 5, 1, -1),
       (13, 5, -1, 1);